//source: https://en.wikipedia.org/wiki/List_of_typefaces
const serif = [
  'Adobe Jenson',
  'Albertus',
  'Aldus',
  'Alexandria',
  'Algerian',
  'American Typewriter',
  'Antiqua',
  'Arno',
  'Aster',
  'Aurora',
  'Baskerville',
  'Bell',
  'Belwe Roman',
  'Bembo',
  'Berkeley Old Style',
  'Bernhard Modern',
  'Bodoni',
  'Bookman',
  'Bulmer',
  'Caledonia',
  'Californian FB',
  'Calisto MT',
  'Cambria',
  'Capitals',
  'Cartier',
  'Caslon',
  'Caslon Antique',
  'Fifteenth Century',
  'Catull',
  'Centaur',
  'Century Old Style',
  'Century Schoolbook',
  'New Century Schoolbook',
  'Century Schoolbook Infant',
  'Charis SIL',
  'Charter',
  'Cheltenham',
  'Clearface',
  'Cochin',
  'Colonna',
  'Computer Modern',
  'Concrete Roman',
  'Constantia',
  'Cooper Black',
  'Copperplate Gothic',
  'Corona',
  'News 705',
  'DejaVu Serif',
  'Didot',
  'Droid Serif',
  'Elephant',
  'Emerson',
  'Excelsior',
  'Fairfield',
  'FF Scala',
  'Footlight',
  'FreeSerif',
  'Friz Quadrata',
  'Garamond',
  'Gentium',
  'Georgia',
  'Gloucester',
  'Goudy Old Style',
  'Goudy',
  'Granjon',
  'High Tower Text',
  'Hoefler Text',
  'IBM Plex Serif',
  'Imprint',
  'Ionic No. 5',
  'News 701',
  'ITC Benguiat',
  'Janson',
  'Jokerman',
  'Joanna',
  'Korinna',
  'Lexicon',
  'Liberation Serif',
  'Linux Libertine',
  'Literaturnaya',
  'Lucida Bright',
  'Melior',
  'Memphis',
  'Miller',
  'Minion',
  'Modern',
  'Mona Lisa',
  'Mrs Eaves',
  'MS Serif',
  'New York',
  'Nimbus Roman',
  'NPS Rawlinson Roadway',
  'OCR A Extended',
  'Palatino',
  'Book Antiqua',
  'Perpetua',
  'Plantin',
  'Playbill',
  'Primer',
  'PT Serif',
  'Renault',
  'Requiem',
  'Rotis Serif',
  'Sabon',
  'Sistina',
  'Souvenir',
  'STIX',
  'Sylfaen',
  'Times New Roman',
  'Times',
  'Torino',
  'Trajan',
  'Trinité',
  'Trump Mediaeval',
  'Utopia',
  'Vera Serif',
  'Wide Latin',
  'Windsor',
  'XITS',
  'Alexandria',
  'American Typewriter',
  'Archer',
  'Athens',
  'Candida',
  'Cholla Slab',
  'City',
  'Clarendon',
  'Concrete Roman',
  'Courier',
  'Egyptienne',
  'Guardian Egyptian',
  'Ionic No. 5',
  'Lexia',
  'Memphis',
  'Nilland',
  'Roboto Slab',
  'Rockwell',
  'Schadow',
  'Serifa',
  'Skeleton Antique',
  'Tower'
];

const sansSerif = [
  'Agency FB',
  'Akzidenz-Grotesk',
  'Andalé Sans',
  'Antique Olive',
  'Arial',
  'Arial Unicode MS',
  'Avant Garde Gothic',
  'Avenir',
  'Bank Gothic',
  'Bauhaus',
  'Bell Centennial',
  'Bell Gothic',
  'Benguiat Gothic',
  'Berlin Sans',
  'Brandon Grotesque',
  'Calibri',
  'Casey',
  'Century Gothic',
  'Charcoal ',
  'Chicago ',
  'Clearview',
  'Comic Sans',
  'Compacta',
  'Corbel',
  'DejaVu Sans',
  'DIN',
  'Dotum',
  'Droid Sans',
  'Dyslexie',
  'Ecofont',
  'Eras',
  'Esseltub',
  'Espy Sans',
  'Eurocrat',
  'Eurostile',
  'Square 721',
  'FF Dax',
  'FF Meta',
  'FF Scala Sans',
  'Fira Sans',
  'Fira Mono',
  'Fira Code',
  'Fira Go',
  'Folio',
  'Franklin Gothic',
  'FreeSans',
  'Frutiger',
  'Futura',
  'Geneva ',
  'Gill Sans',
  'Gill Sans Schoolbook',
  'Gotham',
  'Haettenschweiler',
  'Handel Gothic',
  'Hei',
  'Helvetica',
  'Helvetica Neue',
  'Swiss 721',
  'Highway Gothic',
  'Hobo',
  'IBM Plex Sans',
  'Impact',
  'Industria',
  'Interstate',
  'Johnston',
  'New Johnston',
  'Kabel',
  'Klavika',
  'Lato',
  'Liberation Sans',
  'Linux Biolinum',
  'Lucida Sans',
  'Lucida Grande',
  'Lucida Sans Unicode',
  'Lydian',
  'Meiryo',
  'Meta',
  'Microgramma',
  'Modern',
  'Motorway ',
  'MS Sans Serif ',
  'Myriad',
  'Neutraface',
  'Neuzeit S',
  'News Gothic',
  'Nimbus Sans L',
  'Nordstern',
  'Open Sans',
  'Optima',
  'Overpass',
  'Parisine ',
  'Product Sans',
  'Proxima Nova',
  'PT Sans ',
  'Rail Alphabet',
  'Roboto',
  'Rotis Sans',
  'San Francisco ',
  'Segoe UI',
  'Skia ',
  'Source Sans Pro',
  'Sweden Sans',
  'Syntax',
  'System ',
  'Tahoma',
  'Template Gothic',
  'Thesis Sans',
  'Tiresias',
  'Trade Gothic',
  'Transport ',
  'Trebuchet MS',
  'Twentieth Century ',
  'Ubuntu',
  'Unica',
  'Univers',
  'Zurich',
  'Vera Sans',
  'Verdana'
];

const semiSerif = ['Nyala', 'Rotis Semi Serif', 'Easyreading'];

const monoSpace = [
  '3x3',
  'Andalé Mono',
  'Arial Monospaced',
  'Bitstream Vera',
  'Consolas',
  'Courier',
  'Courier New',
  'DejaVu Sans Mono',
  'Droid Sans Mono',
  'Everson Mono',
  'Fira Mono',
  'Fira Code',
  'Fixed',
  'Fixedsys',
  'HyperFont',
  'IBM Plex Mono',
  'Inconsolata',
  'Letter Gothic',
  'Liberation Mono',
  'Lucida Console',
  'Lucida Sans Typewriter',
  'Lucida Typewriter',
  'Menlo',
  'MICR',
  'Monaco',
  'Monospace',
  'MS Gothic',
  'MS Mincho',
  'Nimbus Mono L',
  'OCR-A',
  'OCR-B',
  'PragmataPro',
  'Prestige Elite ',
  'ProFont',
  'Proggy programming fonts',
  'Roboto Mono',
  'SimHei',
  'SimSun',
  'Source Code Pro',
  'Terminal',
  'Ubuntu Mono',
  'Vera Sans Mono'
];

//source: https://www.npmjs.com/package/css-font-weight-names
const weightsMap = {
  Thin: 100,
  'Extra Light': 200,
  ExtraLight: 200,
  'Ultra Light': 200,
  UltraLight: 200,
  Normal: 400,
  Regular: 400,
  Book: 400,
  Medium: 500,
  'Semi Bold': 600,
  SemiBold: 600,
  'Demi Bold': 600,
  DemiBold: 600,
  'Extra Bold': 800,
  ExtraBold: 800,
  'Ultra Bold': 800,
  UltraBold: 800,
  Bold: 700,
  Light: 300,
  Black: 900,
  Heavy: 900
};

export { serif, sansSerif, semiSerif, monoSpace, weightsMap };
