// display name mappings for invoices and purchase orders
export const displayNames = {
  amount: 'Amount',
  bill_to: 'Bill to',
  buyers: 'Buyer',
  currencies: 'Currency',
  currency: 'Currency',
  due_dates: 'Due date',
  invoice_dates: 'Invoice date',
  invoice_numbers: 'Invoice number',
  invoice_parts: 'Invoice parts',
  invoice_to: 'Invoice to',
  item_description: 'Item description',
  line_items: 'Line item',
  part_description: 'Part description',
  payment_terms: 'Payment terms',
  purchase_order_dates: 'Purchase order date',
  purchase_order_numbers: 'Purchase order number',
  quantity_ordered: 'Quantity',
  ship_to: 'Ship to',
  supplier_ids: 'Supplier id',
  suppliers: 'Suppliers',
  total_amounts: 'Total amount',
  totals_due: 'Total due',
  unit_price: 'Unit price'
};
